### ISSUE TITLE
VS 2015

### ISSUE THREAD

**Issue by mentaman** [visualmutator/visualmutator#1]
I can't install it on vs 2015, only 2013.

**Comment by mentaman** [comment]
Ok I fixed it, I made a pull request.

**Comment by mentaman** [comment]
It works though only with projects that were created in vs 2013,
with projects created in vs 2015 it gives an error "unknown custom metadata item kind 6" when starting new session.

**Comment by marccarre** [comment]
Hi, 
I face similar difficulties using Visual Studio Community 2015.
@mentaman, does your pull request applies to Visual Studio **Community** 2015 too?

Full error details:


     - Microsoft VSIX Installer
     - -------------------------------------------
     - Initializing Install...
     - Extension Details...
     - 	Identifier         : 3dc60cdc-34a8-47e0-87d5-b85ae22ace17
     - 	Name               : VisualMutator
     - 	Author             : PiotrTrzpil
     - 	Version            : 2.0.8
     - 	Description        : VisualMutator info
     - 	Locale             : en-US
     - 	MoreInfoURL        : 
     - 	InstalledByMSI     : False
     - 	SupportedFrameworkVersionRange : [4.5]
     - 
     - 	SignatureState     : Unsigned
     - 	Supported Products : 
     - 		Microsoft.VisualStudio.Pro
     - 			Version : [10.0]
     - 		Microsoft.VisualStudio.Pro
     - 			Version : [11.0]
     - 		Microsoft.VisualStudio.Pro
     - 			Version : [12.0]
     - 
     - 	References         : 
     - 		-------------------------------------------------------
     - 		Identifier   : Microsoft.VisualStudio.MPF
     - 		Name         : Visual Studio MPF
     - 		Version      : [11.0,)
     - 		MoreInfoURL  : 
     - 		Nested       : No
     - 
     - Signature Details...
     - 	Extension is not signed.
     - 
     - Searching for applicable products...
     - Found installed product - Microsoft Visual Studio Community 2015
     - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
     - Found installed product - Global Location
     - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
    at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
    at VSIXInstaller.App.InitializeInstall()
    at System.Threading.Tasks.Task.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()

**Comment by mentaman** [comment]
yes @marccarre I have my self vs comunity 2015.
But I wouldn't recommend using it with vs 2015, it has some problems unfortunately. 
unless you want to dig in in the visualmutator code and fix it. 
I'm a big fan of mutant testing and it's really too bad it's not usable.

**Comment by balarvs2002** [comment]
Is there any plan to fix ? 
http://stackoverflow.com/questions/41431329/mutation-testing-tools-for-visual-studio-2015

**Comment by pavzaj** [comment]
Hello.
Please check my fork
https://github.com/pavzaj/visualmutator

**Comment by pavzaj** [comment]
I have also added pre release page:
https://github.com/pavzaj/visualmutator/releases

Pozdrawiam
Paweł Zając

**Comment by pavzaj** [comment]
There was an error in test execution.
Please check new version:
https://github.com/pavzaj/visualmutator/releases

**Comment by tonymds** [comment]
I confirm [https://github.com/pavzaj/visualmutator](https://github.com/pavzaj/visualmutator) works both on 2015 and 2017. This should be closed and @pavzaj should be made a contributor :P

**Comment by simondel** [comment]
If you happen to use .NET Core you could also try out https://github.com/stryker-mutator/stryker-net (.NET Framework support and integration in Visual Studio is coming in the future)

**Comment by tonymds** [comment]
@simondel looks very good, great to see people investing in this area, I believe that mutation testing is underrated and that there is a plenty of space to evolve
